[03-objects-arrays-intro-to-testing] Solved tasks
js-tasks-ru/js-20210309-2_aleksandr-babich pull request #3
Opened 2021-03-20 09:15 UTC by ibabich88i

2021-03-20 09:15 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-22 09:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const fields = path.split('.');
good 👍

2021-03-22 09:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (result) {
можно избавиться от этой проверки если в `result` сразу присвоить ссылку на `product`

2021-03-22 09:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
помните я говорил о том что с `undefined` мы не работаем напрямую?
необходимо убрать `undefined`

2021-03-22 09:34 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (product.hasOwnProperty(field)) {
подумайте, может от текущего куска кода можно избавиться?

2021-03-22 09:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
просто `return` без `undefined`

2021-03-22 09:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  Object.keys(obj).forEach(key => result[obj[key]] = key);
good 👍

2021-03-22 09:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  for (let i = 0; i < string.length; i++) {
good 👍

2021-03-22 09:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
good 👍

2021-03-22 09:35 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-03-22 09:52 UTC, ibabich88i commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (result) {
Thank you. Fixed for now.

2021-03-22 09:52 UTC, ibabich88i commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
Thank you. Fixed for now.

2021-03-22 09:52 UTC, ibabich88i commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (product.hasOwnProperty(field)) {
Thank you. Deleted this useless part.

2021-03-22 09:53 UTC, ibabich88i commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
Thank you. Fixed for now.

2021-03-23 08:57 UTC, dosandk approved these changes
good 👍

2021-03-23 08:58 UTC, merged